# -*- coding: utf-8 -*-
"""MainFlow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2wLldtsKtVUQ4Hs0j1aoN5J-buWMeu-
"""

import pandas as pd

df = pd.read_csv("/content/Data Cleaning and Preprocessing.csv")
df

df = df.drop_duplicates()
df

# df = df.drop(columns="ChipRate")

# df["string_column"] = df["string_column"].str.strip("_")
# df

# df["phonenumber"] = df["phonenumber"].str.replace('[^a-zA-Z0-9]','')
# df["phonenumber"].apply(lambda x: x[0:3]+'-')

df = df.dropna()
df

import matplotlib.pyplot as plt

plt.show()

import seaborn as sns
sns.boxplot(df['ChipRate'])

